change upload

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -110,7 +110,7 @@ jobs:
         id: run-tests
         run: yarn e2e
 
-      - name: Upload artifacts
+      - name: Upload playwright artifacts
         uses: actions/upload-artifact@v4
         if: ${{ github.repository_owner != 'grafana' && (always() && steps.run-tests.outcome == 'success') || (failure() && steps.run-tests.outcome == 'failure') }}
         with:
@@ -118,11 +118,19 @@ jobs:
           path: playwright-report/
           retention-days: 30
 
-      - name: Publish report to GCS
-        if: ${{ github.repository_owner == 'grafana' && (always() && steps.run-tests.outcome == 'success') || (failure() && steps.run-tests.outcome == 'failure') }}
-        uses: grafana/plugin-actions/publish-report@main
+      - name: Upload playwright videos
+        uses: actions/upload-artifact@v4
+        if: ${{ github.repository_owner != 'grafana' && (always() && steps.run-tests.outcome == 'success') || (failure() && steps.run-tests.outcome == 'failure') }}
         with:
-          grafana-version: ${{ matrix.GRAFANA_IMAGE.VERSION }}
+          name: test-results-${{ matrix.GRAFANA_IMAGE.NAME }}-v${{ matrix.GRAFANA_IMAGE.VERSION }}-${{github.run_id}}
+          path: test-results/
+          retention-days: 30
+
+#      - name: Publish report to GCS
+#        if: ${{ github.repository_owner == 'grafana' && (always() && steps.run-tests.outcome == 'success') || (failure() && steps.run-tests.outcome == 'failure') }}
+#        uses: grafana/plugin-actions/publish-report@main
+#        with:
+#          grafana-version: ${{ matrix.GRAFANA_IMAGE.VERSION }}
 
       - name: Stop grafana docker
         run: docker-compose down
